### ISSUE TITLE
请问Twist层的数如何计算得到的

### ISSUE THREAD

**Issue by htszh** [UIC-ESLAS/ImprovedPlantardArithmetic#3]

**Comment by JunhaoHuang** [comment]
你好，请问你指的是twiddle factor的计算吗？我们在这里（https://github.com/UIC-ESLAS/ImprovedPlantardArithmetic/blob/master/gen_table/m4_kyber ）参考 https://github.com/multi-moduli-ntt-saber/multi-moduli-ntt-saber/tree/master/gen_table 将twist层twiddle factor转换成Plantard域，你可以看看对应的转换过程。至于twist层的twiddle factor具体如何计算，可以查看Multi-moduli NTTs for Saber on Cortex-M3 and Cortex-M4 available at https://tches.iacr.org/index.php/TCHES/article/view/9292/8858 学习相应的理论过程。希望这能帮到你。
